# Generated by Django 5.2.17 on 2026-10-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_seen_at'),
        ('organizations', '0003_unit_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.unit'),
        ),
    ]
